const APPLICATION_CONSTANTS = {
  // SIGNUP
  SIGNUP_REQUIRED_USERNAME: `The user name is required.`,
  SIGNUP_REQUIRED_EMAIL: `The email is required.`,
  SIGNUP_REQUIRED_PASSWORD: `The password is required.`,
  SIGNUP_INVALID_USERNAME: `Invalid Username.
    A minimum of 2 characters are required.`,
  SIGNUP_INVALID_PASSWORD: `Invalid password.
    A minimum of 7 characters are required.`,
  SIGNUP_INVALID_EMAIL: `Invalid Email.
    Please try again!`,
  SIGNUP_EMAIL_REGISTERED: `That email is already registered.`,
  SIGNUP_GENERAL: `Failed to register the user.`,
  SIGNUP_WELCOME_NOTE: `Failed to create the initial note.`,
  INVALID_EMAIL_PASSWORD: "Invalid email and password combination.",
  GENERAL_ERROR: `Something went wrong! Please try again later.`,
  LOGOUT_ERROR: `There was a problem logging out.`,
  LOGIN_ERROR: `There was a problem logging in.`,
  CREATE_NOTEBOOK_ERROR: `Failed to create the Notebook.`,
  CREATE_NOTE_ERROR: `Failed to create the Note.`,
  CREATE_USER_ERROR: `Failed to create User.`,
  CHANGE_USER_ERROR: `Could not update the username.`,
  CHANGE_USER_UNIQUE: `Please enter a new User Name`,
  CHANGE_USER_TOO_FEW: `Please enter a User Name which has at least 3 characters`,
  CHANGE_USER_TOO_MANY: `Please enter a User Name which has less than 10 characters`,
  CHANGE_PASS_UNIQUE: `Both passwords are the same. Please enter a new Password`,
  CHANGE_PASS_TOO_FEW: `Please enter a Password which has at least 3 characters`,
  CHANGE_PASS_TOO_MANY: `Please enter a Password which has less than 7 characters`,
  CHANGE_PASS_LENGTH: `The passwords are different`,
  CHANGE_PASS_ERROR: `Could not change the password.`,
  UNAUTHORIZED: `Unauthorized`,
  UNAUTHORIZED_USER: `Unauthorized User.`,
  UNAUTHORIZED_TOKEN: `Unauthorized Token.`,
  UNAUTHORIZED_JWT: `Unauthorized JWT Token.`,
  USERNAME_MIN: 3,
  USERNAME_MAX: 10,
  PASSWORD_MIN: 7,
  PASSWORD_MAX: 10,
  EMAIL_MIN: 4,
  // NOTEBOOK
  NOTEBOOK_ID_ERROR: `The notebook id is missing.`,
  NOTEBOOK_UPDATED_DATE_MISSING: `The notebook updated date missing.`,
  NOTEBOOK_UPDATED_DATE_ERROR: `Failed to update the notebook date.`,
  NOTEBOOK_ERROR: `Failed to load the Notebook.`,
  NOTEBOOKS_ERROR: `Failed to load the Notebooks.`,
  NOTEBOOKS_NOT_FOUND: `No Notebooks Found.`,
  NOTEBOOKS_DB_ERROR: `No Notebooks returned!`,
  NOTEBOOK_UPDATE_ERROR: `Could not update the notebook!`,
  NOTEBOOK_EDIT_ERROR: `Failed to edit the notebook!`,
  NOTEBOOK_NAME_ERROR: `The notebook name is missing!`,
  NOTEBOOK_COVER_ERROR: `The notebook cover is missing!`,
  NOTEBOOK_CREATE_ERROR: `Failed to create the Notebook!`,
  NOTEBOOK_DELETE_ERROR: `Failed to delete the notebook.`,
  // NOTE
  NOTES_FETCH_ERROR: `Failed to load the Notes.`,
  NOTES_NOT_FOUND: `No Notebooks Found.`,
  NOTE_ID_ERROR: `The note id is missing.`,
  NOTE_ERROR: `Failed to load the Note.`,
  NOTE_SAVE_ERROR: `Failed to save the Note.`,
  NOTE_EMPTY: `The note is empty!`,
  NOTE_CREATE_ERROR: `Could not create the note!`,
  NOTES_DELETE_ID_ERROR: `The note id's are missing.`,
  NOTES_DELETE_ERROR: `Failed to delete the Notes.`,
  NOTES_MOVE_MISSING: `There are no notes to move.`,
  NOTES_MOVE_ERROR: `Failed to move the notes.`,
  // DATABASE
  DB_CONNECT_ERROR: `Could not connect to the database!`,
  DB_CLIENT_ERROR: `Could not connect to the database client!`,
  DB_COLLECTION_ERROR: `Could not connect to the database collection!`,

  // MARKDOWN
  // Special Characters to be converted during Markdown processing.
  SPECIAL_CHARACTERS: [
    { char: "(c)", display: "©" },
    { char: "(C)", display: "©" },
    { char: "(r)", display: "®" },
    { char: "(R)", display: "®" },
    { char: "(TM)", display: "™" },
    { char: "(tm)", display: "™" },
    { char: "(Tm)", display: "™" },
    { char: "(+-)", display: "±" },
    { char: "(P)", display: "℗" },
    { char: "(p)", display: "℗" },
    { char: ":crush:", display: "🥰" },
    { char: ":tear:", display: "🥲" },
  ],
  SPLITSCREEN_MINIMUM_WIDTH: 450,
  VIEWNOTE_PADDING: 69,
  VIEWNOTE_PADDING_MOBILE: 52,
};

export default APPLICATION_CONSTANTS;
