const APPLICATION_CONSTANTS = {
  // SIGNUP
  SIGNUP_REQUIRED_USERNAME: `Username is required.`,
  SIGNUP_REQUIRED_EMAIL: `Email is required.`,
  SIGNUP_REQUIRED_PASSWORD: `Password is required.`,
  SIGNUP_INVALID_USERNAME: `Username must be at least 2 characters.`,
  SIGNUP_INVALID_PASSWORD: `Password must be at least 7 characters.`,
  SIGNUP_INVALID_EMAIL: `Please enter a valid email address.`,
  SIGNUP_EMAIL_REGISTERED: `An account with this email already exists.`,
  SIGNUP_GENERAL: `We couldn't create your account. Please try again.`,
  SIGNUP_WELCOME_NOTE: `We couldn't create your first note. Please try again.`,
  INVALID_EMAIL_PASSWORD: "Invalid email and password combination.",
  GENERAL_ERROR: `Something went wrong! Please try again later.`,
  LOGOUT_ERROR: `There was a problem logging out.`,
  LOGIN_ERROR: `There was a problem logging in.`,
  CREATE_NOTEBOOK_ERROR: `We couldn't create the notebook. Please try again.`,
  CREATE_NOTE_ERROR: `We couldn't create the note. Please try again.`,
  CREATE_USER_ERROR: `We couldn't create your account.`,
  CHANGE_USER_ERROR: `We couldn't update your username. Please try again.`,
  CHANGE_USER_REQUIRED: `Username is required.`,
  CHANGE_USER_UNIQUE: `Please enter a different username.`,
  CHANGE_USER_TOO_FEW: `Username must be at least 3 characters.`,
  CHANGE_USER_TOO_MANY: `Username must be less than 10 characters.`,
  CHANGE_PASS_REQUIRED: `Old password and new password are required.`,
  CHANGE_PASS_UNIQUE: `The new password must be different from your current password.`,
  CHANGE_PASS_TOO_FEW: `Password must be at least 7 characters.`,
  CHANGE_PASS_TOO_MANY: `Password must be less than 10 characters.`,
  CHANGE_PASS_LENGTH: `The two new passwords do not match.`,
  CHANGE_PASS_ERROR: `We couldn't change your password. Please try again.`,
  UNAUTHORIZED: `Your session has expired. Please sign in again.`,
  UNAUTHORIZED_USER: `Your session has expired. Please sign in again.`,
  UNAUTHORIZED_TOKEN: `Your session is no longer valid. Please sign in again.`,
  UNAUTHORIZED_JWT: `Your session is no longer valid. Please sign in again.`,
  USERNAME_MIN: 3,
  USERNAME_MAX: 10,
  PASSWORD_MIN: 7,
  PASSWORD_MAX: 10,
  EMAIL_MIN: 4,
  // NOTEBOOK
  NOTEBOOK_ID_ERROR: `The notebook ID is missing.`,
  NOTEBOOK_UPDATED_DATE_MISSING: `The notebook updated date is missing.`,
  NOTEBOOK_UPDATED_DATE_ERROR: `We couldn't update the notebook date. Please try again.`,
  NOTEBOOK_ERROR: `We couldn't load the notebook. Please try again.`,
  NOTEBOOKS_ERROR: `We couldn't load your notebooks. Please try again.`,
  NOTEBOOKS_NOT_FOUND: `No notebooks found.`,
  NOTEBOOKS_DB_ERROR: `No notebooks returned!`,
  NOTEBOOK_UPDATE_ERROR: `We couldn't update the notebook. Please try again.`,
  NOTEBOOK_EDIT_ERROR: `We couldn't update the notebook. Please try again.`,
  NOTEBOOK_NAME_ERROR: `The notebook name is missing.`,
  NOTEBOOK_COVER_ERROR: `The notebook cover is missing.`,
  NOTEBOOK_CREATE_ERROR: `We couldn't create the notebook. Please try again.`,
  NOTEBOOK_DELETE_ERROR: `We couldn't delete the notebook. Please try again.`,
  // NOTE
  NOTES_FETCH_ERROR: `We couldn't load the notes. Please try again.`,
  NOTES_NOT_FOUND: `No notes found.`,
  NOTE_ID_ERROR: `The note ID is missing.`,
  NOTE_ERROR: `We couldn't load the note. Please try again.`,
  NOTE_SAVE_ERROR: `We couldn't save the note. Please try again.`,
  NOTE_EMPTY: `The note is empty.`,
  NOTE_CREATE_ERROR: `We couldn't create the note. Please try again.`,
  NOTES_DELETE_ID_ERROR: `The note IDs are missing.`,
  NOTES_DELETE_ERROR: `We couldn't delete the notes. Please try again.`,
  NOTES_MOVE_MISSING: `No notes were selected to move.`,
  NOTES_MOVE_ERROR: `We couldn't move the notes. Please try again.`,
  // DATABASE
  DB_CONNECT_ERROR: `Could not connect to the database!`,
  DB_CLIENT_ERROR: `Could not connect to the database client!`,
  DB_COLLECTION_ERROR: `Could not connect to the database collection!`,

  // MARKDOWN
  // Special Characters to be converted during Markdown processing.
  SPECIAL_CHARACTERS: [
    { char: "(c)", display: "©" },
    { char: "(C)", display: "©" },
    { char: "(r)", display: "®" },
    { char: "(R)", display: "®" },
    { char: "(TM)", display: "™" },
    { char: "(tm)", display: "™" },
    { char: "(Tm)", display: "™" },
    { char: "(+-)", display: "±" },
    { char: "(P)", display: "℗" },
    { char: "(p)", display: "℗" },
    { char: ":crush:", display: "🥰" },
    { char: ":tear:", display: "🥲" },
  ],
  SPLITSCREEN_MINIMUM_WIDTH: 450,
  VIEWNOTE_PADDING: 69,
  VIEWNOTE_PADDING_MOBILE: 52,
};

export default APPLICATION_CONSTANTS;
